- name: cart
  hosts: cart
  become: yes
  tasks:
  - name: enable and disable nodejs versions
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 
  
  - name: install Node JS
    ansible.builtin.package:
      name: nodejs
      state: started
  
  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: create application directory
    ansible.builtin.file:
      path: /app
      state: directory
      recurse: yes
      
  - name: download the application folder
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: un-archieve application folder
    ansible.builtin.unarchive:
    src: /tmp/cart.zip
    dest: /app

  - name: installing dependencies
    ansible.builtin.command: npm install 
    args: 
      chdir: /app

  - name: deamon reload
    ansible.builtin.systemd_service:
      daemon-reload: true

  - name: copy mongo-db repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
      enabled: yes  

  - name: enable and start the cart service
    ansible.builtin.service:
    name: cart
    state: restarted
    enabled: yes

  