- name: Catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: enable and disable nodejs versions
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 
  
  - name: install Node JS
    ansible.builtin.package:
      name: nodejs
      state: started
  
  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: create application directory
    ansible.builtin.file:
      path: /app
      state: directory
      recurse: yes
  - name: extract the application folder
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: un-archieve application folder
    ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app

  - name: installing dependencies
    ansible.builtin.command: npm install 
    args: 
      chdir: /app