- name: cart
  hosts: cart
  become: yes
  tasks:
  - name: Install Packages 
    ansible.builtin.package:
      name: "{{item}}"
      loop:
        - python36 
        - gcc 
        - python3-devel
  
  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  
  - name: remove app directory before creating
    ansible.builtin.file: 
      path: /app
      state: absent
  
  - name: creating app directory
    ansible.builtin.file: 
      path: /app
      state: directory
    
  - name: extract the application folder
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/payment.zip
      dest: /tmp

  - name: un-archieve application folder
    ansible.builtin.unarchive:
    src: /tmp/payment.zip
    dest: /app

  - name: installing dependencies
    ansible.builtin.command: pip3.6 install -r requirements.txt
    args: 
      chdir: /app

  - name: copy mongo-db repo
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: deamon reload
    ansible.builtin.systemd_service:
      daemon-reload: true

  - name: enable and start the payment service
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes




      
