- name: redis
  hosts: redis
  become: yes
  tasks: 
  - name: installing rpm repo's
    ansible.builtin.dnf: 
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present
      disable_gpg_check: true

  - name: Enable Redis 6.2 from package streams
    ansible.builtin.command: dnf module enable redis:remi-6.2

  - name: Install Redis
    ansible.builtin.package:
      name: redis
      state: present

  - name: remote configuration changes
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  
  - name: Start & Enable Redis Service
    ansible.builtin.service:
      name: redis
      state: restarted
      enabled: yes