- name: user
  hosts: user
  become: yes
  tasks:
  - name: enable and disable nodejs versions
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 
  
  - name: install Node JS
    ansible.builtin.package:
      name: nodejs
      state: started
  
  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: create application directory
    ansible.builtin.file:
      path: /app
      state: directory
      recurse: yes
      
  - name: extract the application folder
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: un-archieve application folder
    ansible.builtin.unarchive:
    src: /tmp/user.zip
    dest: /app

  - name: installing dependencies
    ansible.builtin.command: npm install 
    args: 
      chdir: /app

  - name: copy mongo-db repo
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: deamon reload
    ansible.builtin.systemd_service:
      daemon-reload: true


  - name: copy mongo-db repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
      enabled: yes  

  - name: get the categories count
    ansible.builtin.command:  mongo --host mongodb.daws76s.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count: {{product_count}}"

  - name: load user data
    ansible.builtin.shell: mongo --host mongodb.daws76s.online < /app/schema/user.js
    when: user_count.stdout == "0" # keep double quotes

  
  - name: enable and start the user service
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes
    