- name: web
  hosts: web
  become: yes
  tasks: 
  - name: install nginx 
    ansible.builtin.package:
      name: nginx 
      state: present
      

  
  - name: remove default contenet
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: remove default contenet
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: directory

  - name: download the application content from url
    ansible.builtin.get_url: 
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp

  - name: extract the web application
    ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

  
  - name: roboshop configuration
    ansible.builtin.copy:
      src: roboshop.conf 
      dest: /etc/nginx/default.d/roboshop.conf

  - name: restart the nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes

